### ISSUE TITLE
unittest failes

### ISSUE THREAD

**Issue by khiltunen** [simphony/simphony-mayavi#111]
I try to get the latest mayavi wrapper installed, put it fails in unittest. 
Ubuntu 12.04LTS on VM
Mayavi version 4.4.3
simphony-common version 0.3.0

python -m unittest discover
Xlib:  extension "RANDR" missing on display "localhost:13.0".
/usr/local/lib/python2.7/dist-packages/traits/etsconfig/etsconfig.py:373: UserWarning: Environment variable "HOME" not set, setting home directory to /tmp
  (environment_variable, parent_directory))
...../root/simphony-mayavi/simphony_mayavi/core/cuba_data_accumulator.py:144: UserWarning: property <CUBA.NAME: 1> is currently ignored
  warnings.warn(message.format(cuba))
....................../root/simphony-mayavi/simphony_mayavi/core/cuba_utils.py:50: UserWarning: ignored property <CUBA.NAME: 1> : not a vector or scalar
  warnings.warn(message.format(cuba))
/root/simphony-mayavi/simphony_mayavi/core/cuba_utils.py:50: UserWarning: ignored property <CUBA.CHEMICAL_SPECIE: 7> : not a vector or scalar
  warnings.warn(message.format(cuba))
/root/simphony-mayavi/simphony_mayavi/core/cuba_utils.py:50: UserWarning: ignored property <CUBA.CRYSTAL_STORAGE: 14> : not a vector or scalar
  warnings.warn(message.format(cuba))
/root/simphony-mayavi/simphony_mayavi/core/cuba_utils.py:50: UserWarning: ignored property <CUBA.NAME_UC: 15> : not a vector or scalar
  warnings.warn(message.format(cuba))
/root/simphony-mayavi/simphony_mayavi/core/cuba_utils.py:50: UserWarning: ignored property <CUBA.LATTICE_VECTORS: 16> : not a vector or scalar
  warnings.warn(message.format(cuba))
/root/simphony-mayavi/simphony_mayavi/core/cuba_utils.py:50: UserWarning: ignored property <CUBA.BOND_LABEL: 19> : not a vector or scalar
  warnings.warn(message.format(cuba))
/root/simphony-mayavi/simphony_mayavi/core/cuba_utils.py:38: UserWarning: ignored property <CUBA.MATERIAL: 68> : not a float or int
  warnings.warn(message.format(cuba))
........................................................................................................................................................................................................................................................................ssssQObject::startTimer: QTimer can only be used with threads started with QThread
EQObject::startTimer: QTimer can only be used with threads started with QThread
EQObject::startTimer: QTimer can only be used with threads started with QThread
E.Segmentation fault (core dumped)

**Comment by kitchoi** [comment]
@khiltunen , Thanks for reporting.
You might need to set the environment variable 
`$ export ETS_TOOLKIT=qt4`
Then could you try again please?
Is it the master branch that you checked out?

**Comment by itziakos** [comment]
I would also suggest reporting the version of Qt and Pyside or PyQt libraries that are used and run the tests with the `-v` option. 

My guess is that It is a test cleanup issue but the segfault is serious.

**Comment by khiltunen** [comment]
Setting the environment variable ETS_TOOLKIT tests goes a little bit further but still failes

QMake version 2.01a
Using Qt version 4.8.1 in /usr/lib/x86_64-linux-gnu

Attached uniittest with -v option

[unittest.txt](https://github.com/simphony/simphony-mayavi/files/90481/unittest.txt)

**Comment by kitchoi** [comment]
@khiltunen the unittest.txt is incomplete.  Could you try again please?  Thanks.

**Comment by khiltunen** [comment]
Here with all output 
[unittest.txt](https://github.com/simphony/simphony-mayavi/files/91444/unittest.txt)

**Comment by kitchoi** [comment]
May I ask what your VTK version is?
Inside python:

```
import vtk
vtk.VTK_VERSION
```

**Comment by khiltunen** [comment]
VTK version is 5.8.0

**Comment by kitchoi** [comment]
Problem resolved after reinstalling following procedures in simphony-framework.  Closing.
