### ISSUE TITLE
test_show fails with wx

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-mayavi#160]
- Need to swap the decorators "check_scene_opened_then_close" with "unittest.skipIf(ETSConfig.toolkit...)" in `test_show.py`
- Possibly add "wx" to .travis.yml to prevent this from happening again

**Comment by stefanoborini** [comment]
which toolkit do we need to use for the product? wx or qt?

**Comment by kitchoi** [comment]
qt is recommended.  But mayavi is designed to work with both wx and qt (historically testing in mayavi is biased towards wx than qt)

**Comment by stefanoborini** [comment]
ok, taking this one

**Comment by kitchoi** [comment]
Fixed by #161, closing.
