### ISSUE TITLE
Using the snapshot function in linux pops up a window

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-mayavi#34]

**Comment by kitchoi** [comment]
problem with mayavi; reference: http://docs.enthought.com/mayavi/mayavi/tips.html#platform-summary

**Comment by kitchoi** [comment]
`mlab.options.offscreen` works on Linux with VTK 5.8+ 
but it does not work on Travis or possibly other headless Linux workstations.  Since users might want to use snapshot on a remote machine, possibly headless as well, it is better to let the window open and close so that the image is correct.

**Comment by stefanoborini** [comment]
I am confused on why it would fail on travis. we start a vfb on travis, and it should work unless the resolution is playing a factor, but I don't see why it should.

In any case, we need to run against the patched version of mayavi to test this. Can we set a dependency against the mayavi branch for that?

**Comment by stefanoborini** [comment]
Doing an experiment to verify this behavior against the proposed mayavi fix

**Comment by itziakos** [comment]
> I am confused on why it would fail on travis. we start a vfb on travis, and it should work unless the resolution is playing a factor, but I don't see why it should.

I think this is an opengl issue.  I have seen this behaviour with other opengl backed libraries like pyglets. If you manage  to suppress the popup you do not get the opengl context to render

**Comment by stefanoborini** [comment]
Closing as wontfix then?

**Comment by kitchoi** [comment]
Let's close it as wontfix
