### ISSUE TITLE
vtk requirement not listed at http://simphony-mayavi.readthedocs.org/en/latest/

### ISSUE THREAD

**Issue by jeremy-rutman** [simphony/simphony-mayavi#88]
The requirement for vtk is not listed at http://simphony-mayavi.readthedocs.org/en/latest/

**Comment by itziakos** [comment]
vtk is a requirement for mayavi not simphony_mayavi.

**Comment by itziakos** [comment]
@jeremy-rutman let me know if you have issues installing `simphony_mayavi`

**Comment by jeremy-rutman** [comment]
so far still attempting to get 'import vtk' to work...but its not a simphony issue , as you mentioned
